[workspace]
members = ["crates/aoc-lib","crates/aoc-tool"]

resolver = "2"

[workspace.dependencies]
anyhow = "1"
itertools = "0.14"
reqwest = { version = "0.12", features = ["blocking"] }
clap = { version = "4", features = ["derive"] }
