[package]
name = "aoc-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
reqwest = { workspace = true }
clap = { workspace = true }

aoc-lib = { path = "../aoc-lib" }
